# Generated by Django 4.1.5 on 2023-01-25 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=1)),
                ("data", models.DateField()),
                ("valor", models.FloatField()),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.TimeField()),
                ("dono_loja", models.CharField(max_length=16)),
                ("nome_loja", models.CharField(max_length=22)),
            ],
        ),
    ]
