# Generated by Django 4.1.5 on 2023-02-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docfile",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("1", "Débito"),
                    ("2", "Boleto"),
                    ("3", "Financiamento"),
                    ("4", "Crédito"),
                    ("5", "Recebimento Empréstimo"),
                    ("6", "Vendas"),
                    ("7", "Recebimento Ted"),
                    ("8", "Recebimento Doc"),
                    ("9", "Aluguel"),
                ],
                max_length=1,
            ),
        ),
    ]
